# Site settings
title: Lambdaspace boilerplate
email: email
description: >
    description
baseurl: "/githubpages-boilerplate" # Add your URL
url: "/githubpages-boilerplate" #Add your URL
twitter_username:
github_username:

# Build settings
markdown: kramdown

include: ['_pages']
