# Site settings
title: Lambdaspace boilerplate
email: email
description: >
    description
baseurl: "" # Add your URL
url: "" #Add your URL
twitter_username:
github_username:

# Build settings
markdown: kramdown

include: ['_pages']
